### ISSUE TITLE
NoSuchMethodException when player joins

### ISSUE THREAD

**Issue by johnnymcmike** [gniftygnome/skylark#3]
Hi, I'm trying to set this up on my server and am getting a server crash from a NoSuchMethodException whenever a player joins. Here is the stack trace:

```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2024-04-05 22:00:52
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.class_270 net.minecraft.class_1657.method_5781()'
        at net.gnomecraft.skylark.config.SkylarkState.getPlayerTeam(SkylarkState.java:203)
        at net.gnomecraft.skylark.config.SkylarkState.getPlayerSpawnPos(SkylarkState.java:125)
        at net.minecraft.class_3222.wrapOperation$zmh000$skylark$getSpawnPos(class_3222.java:5485)
        at net.minecraft.class_3222.method_14245(class_3222.java:288)
        at net.minecraft.class_3222.<init>(class_3222.java:283)
        at net.minecraft.class_3324.method_14613(class_3324.java:439)
        at net.minecraft.class_8610.method_52408(class_8610.java:126)
        at net.minecraft.class_8736.method_53043(class_8736.java:20)
        at net.minecraft.class_8736.method_11054(class_8736.java:7)
        at net.minecraft.class_2600.method_11072(class_2600.java:24)
        at net.minecraft.class_3738.run(class_3738.java:18)
        at net.minecraft.class_1255.method_18859(class_1255.java:156)
        at net.minecraft.class_4093.method_18859(class_4093.java:23)
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797)
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165)
        at net.minecraft.class_1255.method_16075(class_1255.java:130)
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779)
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773)
        at net.minecraft.class_1255.method_18857(class_1255.java:139)
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:758)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Messing with the config file doesn't seem to do anything about this. I'm using the latest build from Modrinth on a 1.20.4 server.

**Comment by gniftygnome** [comment]
The method still exists but it's apparently moved.  I probably need to rebuild for 1.20.4.

**Comment by johnnymcmike** [comment]
Gotcha. I just tried reverting to the 1.20.1 build out of curiosity and got a different NoSuchMethodException for `readState` when trying to initialize the level. Just let me know when the new build is up.

**Comment by gniftygnome** [comment]
Try this one.  https://modrinth.com/mod/skylark/version/1.2.0-beta.1

**Comment by johnnymcmike** [comment]
This one works Hope that information is helpful to you lol

**Comment by gniftygnome** [comment]
Excellent.  It's always good to confirm.
